WindowManager:
    HomeWindow:
    InstructionWindow:
    AboutWindow:
    ChoiceWindow:
    PreprogrammedWindow:
    BlastWindow:
    ToolsWindow:
    UniprotWindow:
    PfamWindow:
    FrustWindow:
    PymolWindow:
    WaltzWindow:
    CamsolWindow:
    LogprotWindow:
    MainWindow:
    SecondWindow:
    ProteinWindow:
    ExpressionWindow:
    WrongWindow:
    BacterialWindow:
    PurificationWindow:
    IonExchangeWindow:
    iex2Window:
    iex2bWindow:
    iex3Window:
    Expression3Window:
    Expression4Window:
    BamhiWindow:
    StickyAmpicilinWindow:
    LastExpressionWindow:
    LacWindow:
    SECWindow:
    SEC2Window
    BackPurificationWindow:
    AffinityWindow:
    HydrophobicWindow:
    hic2Window:
    hic3Window:
    AffinityQuestionWindow:
    FinalWindow:
    AffinityQbWindow:
    AffinityQcWindow:
    AffinityQdWindow:
    AffinityQeWindow:

<HomeWindow>:
    name: "home"

    GridLayout:
        cols: 1
        size: root.width, root.height

        Label:
            text: "Welcome to Aloha BioChemistry App"
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"

        Button:
            text: "[color=#0B383C][b]Module 1: [/b]Bioinformatic Tools[/color]"
            markup: True
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_release:
                app.root.current = "choice"
            background_color: (2.21, 2.36, 1.91, 1)

        Button:
            text: "[color=#0B383C][b]Module 2: [/b]Protein Expression[/color]"
            markup: True
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_release:
                app.root.current = "expression"
            background_color: (1.94, 2.27, 2.10, 1)

        Button:
            text: "[color=#0B383C][b]Module 3: [/b]Protein Purification[/color]"
            markup: True
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_release:
                app.root.current = "purification"
            background_color: (1.68, 2.16, 2.20, 1)

        GridLayout:
            cols: 2

            Button:
                text: "Quick instructions"
                text_size: root.width, None
                size: self.texture_size
                halign: "center"
                valign: "center"

                on_release:
                    app.root.current = "instruction"

            Button:
                text: "Reset"
                text_size: root.width, None
                size: self.texture_size
                halign: "center"
                valign: "center"

                on_release:
                    root.remove_files()

            Button:
                text: "Links to tools"
                text_size: root.width, None
                size: self.texture_size
                halign: "center"
                valign: "center"

                on_release:
                    app.root.current = "linkstools"

            Button:
                text: "Links to videos"
                text_size: root.width, None
                size: self.texture_size
                halign: "center"
                valign: "center"

                on_release:
                    app.root.current = "linksvideo"

            Button:
                text: "References"
                text_size: root.width, None
                size: self.texture_size
                halign: "center"
                valign: "center"

                on_release:
                    app.root.current = "refs"

            Button:
                text: "About Aloha BioChemistry"
                text_size: root.width, None
                size: self.texture_size
                halign: "center"
                valign: "center"

                on_release:
                    app.root.current = "about"


<InstructionWindow>:
    name: "instruction"

    GridLayout:
        cols: 1

        Label:
            text: "It is recommended you follow the modules in order, but it is not necessary.\n\nClicking outside of a popup window or pressing [i]esc[/i] will close it.\n\n[u]Underlined text[/u] symbolizes a clickable link.\n\nReset button on the Home window deletes any data generated through a live BLAST search. It is recommended when switching the query amino acid sequence.\n\nIf you run into problems displaying images within the app, switch to a full-screen mode."
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            markup: True

        Label:
            text:""

        Button:
            text: "Go back to Home"
            on_release:
                app.root.current = "home"
                root.manager.transition.direction = "right"
            background_color: (0.51, 0.34, 1.36, 1)

<AboutWindow>:
    name: "about"

    GridLayout:
        cols:1
        size: root.width, root.height

        Label:
            text: "Aloha Biochem was developed for [u][ref=abc]University of Hawaii[/ref][/u]"
            markup: True
            on_ref_press:
                import webbrowser
                webbrowser.open("https://manoa.hawaii.edu/")

        Label:
            text: "Corresponding Author: Dr. Ellinor Haglund ellinorh@hawaii.edu\n\n Code written by Paulina Panek\n\n Content developed by Jennifer Simien, Paulina Panek, and Ellinor Haglund"

        Button:
            text: "UH"
            on_release:
                root.OpenLink()
        Button:
            text: "Go back to Home"
            on_release:
                app.root.current = "home"
                root.manager.transition.direction = "right"
            background_color: (0.51, 0.34, 1.36, 1)

<ChoiceWindow>:
    name: "choice"

    GridLayout:
        cols:1
        size: root.width, root.height

        GridLayout:
            cols:1

            Label:
                text: "You can choose to learn about Ribosomal Protein Subunit 6 (S6) [fast]\n\nOR\n\ndo a live search of any protein sequence [slow]."
                text_size: root.width, None
                size: self.texture_size
                halign: "center"
                valign: "center"

            Button:
                text: "Show data for S6"
                text_size: root.width, None
                size: self.texture_size
                halign: "center"
                valign: "center"
                on_release:
                    app.root.current = "preprogrammed"

            Button:
                text: "Live search\n(requires internet connection)"
                text_size: root.width, None
                size: self.texture_size
                halign: "center"
                valign: "center"
                on_release:
                    app.root.current = "main"

            Button:
                text: "Go back to Home"
                text_size: root.width, None
                size: self.texture_size
                halign: "center"
                valign: "center"
                on_release:
                    app.root.current = "home"
                background_color: (0.51, 0.34, 1.36, 1)

<PreprogrammedWindow>:
    name: "preprogrammed"

    GridLayout:
        cols:1
        size: root.width, root.height

        Label:
            text: "This window is preprogrammed for protein S6\n- it does not update.\n\nName of the species the protein came from is in square brackets [  ]."
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"

        Label:
            text: "30S ribosomal protein S6 [Thermus thermophilus]"
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"

        Label:
            text: "Weight of this protein is:\n\n 11.931 kDa"
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"

        Button:
            text: "Learn more about how we got this result from BLAST"
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_release:
                app.root.current = "blast"

        Button:
            text: "Go back to Home"
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_release:
                app.root.current = "home"
            background_color: (0.51, 0.34, 1.36, 1)

<BlastWindow>:
    name: "blast"

    GridLayout:
        cols:1
        size: root.width, root.height
        Label:
            text: "[u][ref=abcd]BLAST[/ref][/u] is the most cited tool for aligning genetic and protein sequences across different organisms. This allows users to determine the species origin of proteins/genes as well as determine homologs of the protein/gene of choice."
            markup: True
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_ref_press:
                import webbrowser
                webbrowser.open("https://blast.ncbi.nlm.nih.gov/Blast.cgi")

        Label:
            text: "There are four types of BLAST:\n1. nBLAST for searching DNA sequences against DNA database,\n2. pBLAST for searching amino acid sequences against amino acid database,\n3. BLASTx for searching translated nucleotides against amino acid database,\n4. tBLASTn for searching proteins against translated nucleotide databases."
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"

        Button:
            size_hint_y: 0.5
            text: "Learn about other bioinformatic tools"
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_release:
                app.root.current = "tools"

        Button:
            size_hint_y: 0.5
            text: "Go back to Home"
            on_release:
                app.root.current = "home"
            background_color: (0.51, 0.34, 1.36, 1)

<ToolsWindow>:
    name: "tools"

    GridLayout:
        cols:2

        GridLayout:
            cols: 1

            Label:
                size_hint_y: 0.3
                text: "Following tools are available:"

            GridLayout:
                cols: 2

                Button:
                    text: "[color=#0B383C][b]UniProt[/color][/b]"
                    markup: True
                    on_release:
                        app.root.current = "uniprot"
                    background_color: (2.08, 2.31, 2.02, 1)

                Button:
                    text: "[color=#0B383C][b]Pfam[/color][/b]"
                    markup: True
                    on_release:
                        app.root.current = "pfam"
                    background_color: (2.08, 2.31, 2.02, 1)

                Button:
                    text:  "[color=#0B383C][b]Frutratometer[/color][/b]"
                    markup: True
                    on_release:
                        app.root.current = "frust"
                    background_color: (1.81, 2.21, 2.16, 1)

                Button:
                    text:  "[color=#0B383C][b]PyMOL[/color][/b]"
                    markup: True
                    on_release:
                        app.root.current = "pymol"
                    background_color: (1.81, 2.21, 2.16, 1)

                Button:
                    text:  "[color=#0B383C][b]Waltz[/color][/b]"
                    markup: True
                    on_release:
                        app.root.current = "waltz"
                    background_color: (1.55, 2.10, 2.25, 1)

                Button:
                    text:  "[color=#0B383C][b]Camsol[/color][/b]"
                    markup: True
                    on_release:
                        app.root.current = "camsol"
                    background_color: (1.55, 2.10, 2.25, 1)

                Button:
                    text: "[color=#0B383C][b]WebLogo Plot[/color][/b]"
                    markup: True
                    on_release:
                        app.root.current = "logprot"
                    background_color: (1.29, 1.96, 2.31, 1)

                Button:
                    text:  "[color=#0B383C][b]BLAST[/color][/b]"
                    markup: True
                    on_release:
                        app.root.current = "blast"
                    background_color: (1.29, 1.96, 2.31, 1)

            Button:
                size_hint_y: 0.25
                text: "Go back to Home"
                on_release:
                    app.root.current = "home"
                    root.manager.transition.direction = "right"
                background_color: (0.51, 0.34, 1.36, 1)

<UniprotWindow>:
    name: "uniprot"

    GridLayout:
        cols:1
        size: root.width, root.height

        Label:
            text: "[u][ref=uniprot]UniProt[/u][/ref] is a data base of proteins that organizes proteomes of organisms, as well as sequence clusters of proteins. It is used to annotate protein encoding genes of geneomes and can be used to examine homologous protein families.\n\nUniProt is connected to other institutions and data bases: European Bioinformatics Institute (EMBL-EBI) and Swiss Institute of Bioinformatics (SIB), and Protein Information Resource (PIR). Collectively, these databases are peer-reviewed for quality resources to be accessed around the world.\n\nUniProt can be used in addition to BLAST to compare queried protein sequences to other proteins that have been examined."
            markup: True
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_ref_press:
                import webbrowser
                webbrowser.open("https://www.uniprot.org/")

        Button:
            size_hint_y: 0.3
            text: "Go back to list of bioinformatic tools"
            on_release:
                app.root.current = "tools"

        Button:
            size_hint_y: 0.3
            text: "Go back to Home"
            on_release:
                app.root.current = "home"
            background_color: (0.51, 0.34, 1.36, 1)

<PfamWindow>:
    name: "pfam"

    GridLayout:
        cols:1
        size: root.width, root.height

        Label:
            text: "Homologous proteins across different organisms are organized in [u][ref=pfam]Pfam[/u][/ref]."
            markup: True
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_ref_press:
                import webbrowser
                webbrowser.open("https://pfam.xfam.org/")

        Button:
            size_hint_y: 0.3
            text: "Go back to list of bioinformatic tools"
            on_release:
                app.root.current = "tools"

        Button:
            size_hint_y: 0.3
            text: "Go back to Home"
            on_release:
                app.root.current = "home"
            background_color: (0.51, 0.34, 1.36, 1)

<FrustWindow>:
    name: "frust"

    GridLayout:
        cols:1
        size: root.width, root.height

        Label:
            text: "Energetically favored and disfavored interactions between amino acid side chains can be quantitatively assessed based on their proximity in space solved by experimental data (NMR, CryoEM, X-Ray crystallography). [u][ref=frust]The frustratometer[/u][/ref] can predict how point mutations in a protein can increase or decrease frustration of the protein based on the protein sequence. This can be used to drive site specific mutations for in vitro studies. The frustrometer can also be used to predic secondary structure of protein sequences. Collectively this software is beneficial for supporting or driving experimental research.\n\nProtein Frustratometer 2: a tool to localize energetic frustration in protein molecules, now with electrostatics."
            markup: True
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_ref_press:
                import webbrowser
                webbrowser.open("http://frustratometer.qb.fcen.uba.ar/")

        Button:
            size_hint_y: 0.3
            text: "Go back to list of bioinformatic tools"
            on_release:
                app.root.current = "tools"

        Button:
            size_hint_y: 0.3
            text: "Go back to Home"
            on_release:
                app.root.current = "home"
            background_color: (0.51, 0.34, 1.36, 1)

<PymolWindow>:
    name: "pymol"

    GridLayout:
        cols:1
        size: root.width, root.height

        Label:
            text: "[ref=pymol][u]PyMOL[/u][/ref] is a widely used macromolecular visualization tools. It is an open source molecular graphics tool used to visualize 3D structure of proteins, nucleic acids, small molecules electron densities, surfaces and trajectories. The visualization of structures in PyMOL are based on experimental data of NMR, X-Ray crystallography, or Cryo-EM.\n\nApart from the visualization of structures, PyMOL can be used as an enhanced analysis tool for:\n- study protein-protein interactions,\n- protein-ligand docking,\n- real-time energy minimizing structures,\n- secondary structure prediction,\n- generating Ramachandran plots,\n- electrostatic map calculations,\n- predictions of protein function.\n\nPyMOL is written in Python, one of the most popular programming languages, and it can be extended to Python plugins easily."
            markup: True
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_ref_press:
                import webbrowser
                webbrowser.open("https://pymol.org/2/")

        Button:
            size_hint_y: 0.3
            text: "Go back to list of bioinformatic tools"
            on_release:
                app.root.current = "tools"
        Button:
            size_hint_y: 0.3
            text: "Go back to Home"
            on_release:
                app.root.current = "home"
            background_color: (0.51, 0.34, 1.36, 1)

<WaltzWindow>:
    name: "waltz"

    GridLayout:
        cols:1
        size: root.width, root.height

        Label:
            text: "Some neurodegenerative diseases are caused by amyloid fiber formation of proteins, for example, Amyotrophic Lateral Sclerosis (ALS), Parkinson's, and Alzheimer's diseases.\n\nAmino acids have different propensities for amyloid formation. [ref=waltz][u]WALTZ[/u][/ref] predicts regions of the protein sequences prone to amyloid formation."
            markup: True
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_ref_press:
                import webbrowser
                webbrowser.open("https://omictools.com/waltz-tool")

        Button:
            size_hint_y: 0.3
            text: "Go back to list of bioinformatic tools"
            on_release:
                app.root.current = "tools"

        Button:
            size_hint_y: 0.3
            text: "Go back to Home"
            on_release:
                app.root.current = "home"
            background_color: (0.51, 0.34, 1.36, 1)

<CamsolWindow>:
    name: "camsol"

    GridLayout:
        cols:1
        size: root.width, root.height

        Label:
            text: "[u][ref=camsol]CamSol[/u][/ref] works by performing a rapid computational screening of tens of thousand\nof mutations to identify those with the greatest impact on the solubility of\nthe target protein while maintaining its native state and biological activity. It is a method for the rational design of protein variants with enhanced solubility."
            markup: True
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_ref_press:
                import webbrowser
                webbrowser.open("https://omictools.com/camsol-tool")

        Button:
            size_hint_y: 0.3
            text: "Go back to list of bioinformatic tools"
            on_release:
                app.root.current = "tools"

        Button:
            size_hint_y: 0.3
            text: "Go back to Home"
            on_release:
                app.root.current = "home"
            background_color: (0.51, 0.34, 1.36, 1)

<LogprotWindow>:
    name: "logprot"

    GridLayout:
        cols:1
        size: root.width, root.height

        Label:
            text: "[u][ref=weblogo]WebLogo Plot[/ref][/u] is a graphical way to quickly determine conserved amino acid residues in protein sequences within a family of proteins. "
            markup: True
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_ref_press:
                import webbrowser
                webbrowser.open("https://weblogo.berkeley.edu/logo.cgi")


        Button:
            size_hint_y: 0.3
            text: "Go back to list of bioinformatic tools"
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_release:
                app.root.current = "tools"

        Button:
            size_hint_y: 0.3
            text: "Go back to Home"
            on_release:
                app.root.current = "home"
            background_color: (0.51, 0.34, 1.36, 1)

<MainWindow>:
    name: "main"
    sequence: sequence

    GridLayout:
        cols:1
        size: root.width, root.height

        GridLayout:
            cols:2

            Label:
                text: "Paste the sequence from the FASTA file.\nInclude the header.\n\nUse Ctrl+C to paste the sequence.\n\nYou can enter any amino acid sequence."
                text_size: root.width, None
                size: self.texture_size
                halign: "center"
                valign: "center"

            TextInput:
                id: sequence
                multinline: False

        Button:
            text:"Submit"
            on_release:
                root.btn()
                app.root.current = "second"

        Button:
            text: "Go back to Home"
            on_release:
                app.root.current = "home"
            background_color: (0.51, 0.34, 1.36, 1)

<SecondWindow>:
    name: "second"
    inputfasta: inputfasta

    GridLayout:
        cols:1
        size: root.width, root.height

        Label:
            text: "We will use Basic Local Alignment Search Tool (BLAST) to find out the identity of this protein."
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"

        Image:
            source: 'BLAST1.PNG'
            size: self.texture_size

        Label:
            text: "Is the following sequence correct?"
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"

        Label:
            id: inputfasta
            text: "The sequence you entered should appear here. If you don't see it, start over."
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"

        Image:
            source: 'BLAST2.PNG'
            size: self.texture_size

        Button:
            text: "Let's do this!"

            on_release:
                app.root.current = "protein"
                root.blastsearch()
                root.manager.transition.direction = "left"

        Button:
            text: "I made an error, take me back."
            on_release:
                app.root.current = "main"
                root.manager.transition.direction = "right"

<ProteinWindow>:
    name: "protein"
    protname: protname
    weight: weight

    GridLayout:
        cols:1
        size: root.width, root.height

        Label:
            text: "Your protein was identified!"

        Label:
            text: "Name of the species it came from is in square brackets [  ]"
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"

        Label:
            id: protname
            text: "Something went wrong, try again!"

        Label:
            text: "Weight of this protein is:"
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
        Label:
            id: weight
            text: "The weight should appear here, something went wrong"
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
        Button:
            text: "Learn more about BLAST"
            on_release:
                app.root.current = "blast"
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
        Button:
            text: "Go back to Home"
            on_release:
                app.root.current = "home"
            background_color: (0.51, 0.34, 1.36, 1)

<ExpressionWindow>:
    name: "expression"

    GridLayout:
        cols: 1

        Label:
            text: "To study a protein, you need to have a sample.\nHow would you produce your protein?"
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"

        Button:
            size_hint_x: 0.5
            text: "Review protein expression"
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_release:
                root.showrevexp()
            background_color: (0.68, 1.70, 1.53, 1)

        Button:
            text: "Mammalian cell culture"
            on_release:
                app.root.current = "wrong"

        Button:
            text: "Order it on Amazon"
            on_release:
                app.root.current = "wrong"

        Button:
            text: "Bacterial cell culture"
            on_release:
                app.root.current = "bacterial"

        Button:
            text: "Order it on Fisher Scientific"
            on_release:
                app.root.current = "wrong"

        Button:
            text: "Go back to Home"
            on_release:
                app.root.current = "home"
            background_color: (0.51, 0.34, 1.36, 1)

<BacterialWindow>:
    name: "bacterial"

    GridLayout:
        cols: 1

        Label:
            text: "You need a circular vector to express your protein in bacteria.\nFor example, pET-3A vector can be used.\n\nHow many kilobases (kb) are in an uncloned pET3A vector?"
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"

        GridLayout:
            cols: 2

            Button:
                text: "Review vectors"
                on_release:
                    root.revvec()
                background_color: (0.68, 1.70, 1.53, 1)

            Button:
                text: "Show pET-3A vector"
                on_release:
                    root.showpet()
                background_color: (1.36, 2.04, 2.38, 1)


        Button:
            text: "3"
            on_release:
                app.root.current = "wrong"

        Button:
            text: "4.6"
            on_release:
                app.root.current = "expression3"

        Button:
            text: "10"
            on_release:
                app.root.current = "wrong"

        Button:
            text: "30"
            on_release:
                app.root.current = "wrong"
        Button:
            text: "Go back to Home"
            on_release:
                app.root.current = "home"
                root.manager.transition.direction = "right"
            background_color: (0.51, 0.34, 1.36, 1)


<Expression3Window>:
    name: "expression3"

    GridLayout:
        cols: 1

        Label:
            text: "How do you incorporate a desired gene into the vector?"
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"

        Button:
            text: "Heat shock"
            on_release:
                app.root.current = "wrong"

        Button:
            text: "Restriction enzymes"
            on_release:
                app.root.current = "expression4"

        Button:
            text: "Synthesize the vector from the bases in a correct sequence."
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_release:
                app.root.current = "wrong"

        Button:
            text: "Mix the vectors and the DNA for 24h in acidic solution."
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_release:
                app.root.current = "wrong"

        Button:
            text: "Go back to Home"
            on_release:
                app.root.current = "home"
                root.manager.transition.direction = "right"
            background_color: (0.51, 0.34, 1.36, 1)

<Expression4Window>:
    name: "expression4"

    GridLayout:
        cols: 1

        Label:
            text: "Which restriction enzyme would work with this vector?"
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"

        Button:
            text: "Show the sequence of pET-3A"
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_release:
                root.showpetseq()
            background_color: (1.36, 2.04, 2.38, 1)

        Button:
            text: "NdeI"
            on_release:
                app.root.current = "wrong"

        Button:
            text: "BamHI"
            on_release:
                app.root.current = "bamhi"

        Button:
            text: "EcoRI"
            on_release:
                app.root.current = "wrong"

        Button:
            text: "NcoI"
            on_release:
                app.root.current = "wrong"

        Button:
            text: "Go back to Home"
            on_release:
                app.root.current = "home"
                root.manager.transition.direction = "right"
            background_color: (0.51, 0.34, 1.36, 1)
<P>:
    Label:
        id: pet3aseq
        text: "this should not show"
        text_size: root.width, None
        size: self.texture_size

<BamhiWindow>:
    name: "bamhi"

    GridLayout:
        cols: 1

        Label:
            text: "Restriction enzymes produce either sticky or blunt ends.\nWhich ones are more desirable for vector incorporation?"
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"

        Button:
            text: "Show sticky and blunt ends example"
            on_release:
                root.showends()
            background_color: (1.36, 2.04, 2.38, 1)

        Button:
            text: "Blunt ends are more desirable."
            on_release:
                app.root.current = "wrong"

        Button:
            text: "Sticky ends are more desirable."
            on_release:
                app.root.current = "stickyampicilin"

        Button:
            text: "Go back to Home"
            on_release:
                app.root.current = "home"
                root.manager.transition.direction = "right"
            background_color: (0.51, 0.34, 1.36, 1)

<StickyAmpicilinWindow>:
    name: "stickyampicilin"

    GridLayout:
        cols: 1

        Label:
            text: "How do you determine if bacteria picked up the vector?"
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"

        Button:
            text: "All bacteria always pick up the vector."
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_release:
                app.root.current = "wrong"

        Button:
            text: "Various stains are used to verify that."
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_release:
                app.root.current = "wrong"

        Button:
            text: "The leftover vector concentration is quantified."
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_release:
                app.root.current = "wrong"

        Button:
            text: "Vector contains antibiotic resistance genes, so only those bacteria survive."
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_release:
                app.root.current = "lac"

        Button:
            text: "Go back to Home"
            on_release:
                app.root.current = "home"
                root.manager.transition.direction = "right"
            background_color: (0.51, 0.34, 1.36, 1)

<LacWindow>:
    name: "lac"

    GridLayout:
        cols: 1

        Label:
            text: "How do you control when the desired protein is expressed?"
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"

        Button:
            text: "Review bacterial expression"
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_release:
                root.bacexp()
            background_color: (0.68, 1.70, 1.53, 1)

        Button:
            text: "By changing the incubation temperature of the bacteria."
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_release:
                app.root.current = "wrong"

        Button:
            text: "By addition of lysozyme, which induces the lac operon."
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_release:
                app.root.current = "wrong"

        Button:
            text: "By addition of Isopropyl thiogalactopyranoside (IPTG), which induces the lac operon."
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_release:
                app.root.current = "lastexpression"

        Button:
            text: "By treatment with cyanogen bromide, which inhibits other proteins."
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_release:
                app.root.current = "wrong"

        Button:
            text: "Go back to Home"
            on_release:
                app.root.current = "home"
                root.manager.transition.direction = "right"
            background_color: (0.51, 0.34, 1.36, 1)

<LastExpressionWindow>:
    name: "lastexpression"

    GridLayout:
        cols: 1

        Label:
            text: "Correct! You are done with the expression module!\n\nTo release bacterial recombinantly expressed proteins from the cells to purify in vitro, there are three main methods of lysing cells. Sonication, arguably the most widely used due to its ease of use, uses sonic waves at\nhigh frequencies to lyse cells."
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"

        Label:
            text: "Proteins can be purified in a variety of ways, depending on characteristic attributes of the protein of choice. These characteristics include solubility, temperature of denaturant, isoelectric point (pI). Before column chromatography, some proteins are purified using solubility or temperature as the varied method. Some proteins are soluble at high salt concentrations and other proteins are not, and therefore adding ammonium sulfate to a homogenate of protein can separate out the target protein.\n\nAfter these steps, column chromatography can be used"
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"

        Button:
            size_hint_y: 0.4
            text: "Continue to Purification Module"
            on_release:
                app.root.current = "purification"

        Button:
            text: "Go back Home"
            size_hint_y: 0.4
            on_release:
                app.root.current = "home"
                root.manager.transition.direction = "right"
            background_color: (0.51, 0.34, 1.36, 1)

<PurificationWindow>:
    name: "purification"

    GridLayout:
        cols:1

        Label:
            text: "Following methods are available:"
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"

        Button:
            text: "[color=#0B383C][b] Size-exclusion chromatography\n(SEC)[/color][/b]"
            markup: True
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_release:
                app.root.current = "sec"
            background_color: (1.68, 2.16, 2.20, 1)

        Button:
            text: "[color=#0B383C][b]Ion-exchange chromatography\n(IEX)[/color][/b]"
            markup: True
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_release:
                app.root.current = "ionexchange"
            background_color: (1.41, 2.03, 2.28, 1)

        Button:
            text: "[color=#0B383C][b]Hydrophobic interaction chromatography\n(HIC)[/b][/color]"
            markup: True
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_release:
                app.root.current = "hydrophobic"
            background_color:(1.23, 1.88, 2.31, 1)

        Button:
            text: "[color=#0B383C][b]Affinity chromatography\n(AC)[/b][/color]"
            markup: True
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_release:
                app.root.current = "affinity"
            background_color:  (1.36, 1.65, 2.21, 1)

        Button:
            text: "Go back to Home"
            on_release:
                app.root.current = "home"
                root.manager.transition.direction = "right"
            background_color: (0.51, 0.34, 1.36, 1)

<IonExchangeWindow>:
    name: "ionexchange"

    GridLayout:
        cols: 1
        Label:
            text: "In ion-exchange chromatography, charged molecules in the sample are separated by the electrostatic forces of attraction when passed through the ionic resin at particular pH and temperature.\n\nThe separation occurs by reversible exchange of ions between the ions present in the solution and those present in the ion exchange resin."
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
        Button:
            text: "Show me how it works!"
            on_release:
                root.showiex()
            background_color: (1.36, 2.04, 2.38, 1)

        Button:
            text: "Continue to next question"
            on_release:
                app.root.current = "iex2"

        Button:
            text: "Go back to Home"
            on_release:
                app.root.current = "home"
            background_color: (0.51, 0.34, 1.36, 1)

<iex2Window>:
    name: "iex2"
    isoelectric: isoelectric

    GridLayout:
        cols: 1

        Label:
            text: "IEX column may use a positive or negative resin. For the protein to bind, buffer with proper pH must be selected."
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"

        Button:
            text: "Show me the rules of buffer selection."
            on_release:
                root.showiexrule()
            background_color: (1.36, 2.04, 2.38, 1)
        Label:
            id: isoelectric
            text: "You pI should be displayed here."

        Button:
            text: "Continue to next question. You will need information from this window to answer."
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_release:
                app.root.current = "iex2b"
        Button:
            text: "Go back to Home"
            on_release:
                app.root.current = "home"
                root.manager.transition.direction = "right"
            background_color: (0.51, 0.34, 1.36, 1)

<iex2bWindow>:
    name: "iex2b"

    GridLayout:
        cols: 1
        Label:
            text: "In cation exchange chromatography:"
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"

        Button:
            text: "The molecule of interest and resin are both positive."

            on_release:
                app.root.current = "wrong"
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"

        Button:
            text: "The molecule of interest is positive and the resin in negative."
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_release:
                app.root.current = "iex3"

        Button:
            text: "The molecule of interest is negative and the resin is positive."
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_release:
                app.root.current = "wrong"

        Button:
            text: "The molecule of interest and resin are both negative."
            on_release:
                app.root.current = "wrong"
        Button:
            text: "Go back to Home"
            on_release:
                app.root.current = "home"
                root.manager.transition.direction = "right"
            background_color: (0.51, 0.34, 1.36, 1)

<iex3Window>:
    name: "iex3"

    GridLayout:
        cols: 1
        Label:
            text: "If the resin has a negative charge and pI = 6.3, what is a good pH for the buffer used IEX?"
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"

        Button:
            text: "7.5"
            on_release:
                app.root.current = "wrong"

        Button:
            text: "6.3"
            on_release:
                app.root.current = "wrong"

        Button:
            text: "5.0"
            on_release:
                app.root.current = "backPurification"

        Button:
            text: "4.0"
            on_release:
                app.root.current = "wrong"

        Button:
            text: "Go back to Home"
            on_release:
                app.root.current = "home"
                root.manager.transition.direction = "right"
            background_color: (0.51, 0.34, 1.36, 1)

<SECWindow>:
    name: "sec"

    GridLayout:
        cols: 1
        Label:
            text: "In size- exclusion chromatography, molecules are separated based on their size as they pass through a resin packed column.\n\nChoose the correct statement below:"
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"

        Button:
            text: "Show me how it works!"
            on_release:
                root.showSEC()
            background_color: (1.36, 2.04, 2.38, 1)

        Button:
            text: "Larger molecules are eluted faster, because they are heavier."
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_release:
                app.root.current = "wrong"

        Button:
            text: "Larger molecules are eluted faster, because they don't get trapped in the resin pores."
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_release:
                app.root.current = "sec2"

        Button:
            text: "Go back to Home"
            on_release:
                app.root.current = "home"
                root.manager.transition.direction = "right"
            background_color: (0.51, 0.34, 1.36, 1)

<SEC2Window>:
    name: "sec2"

    GridLayout:
        cols: 1

        Label:
            text: "What do you think is the main downside of SEC?"
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"

        Button:
            text: "E.coli might produce a protein that has the same size as the target protein."
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_release:
                app.root.current = "backPurification"

        Button:
            text: "The protein might be cleaved by the resin."
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_release:
                app.root.current = "wrong"

        Button:
            text: "This technique only works in a narrow pH range."
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_release:
                app.root.current = "wrong"

        Button:
            text: "Sometimes proteins bind irreversibly with the resin."
            on_release:
                app.root.current = "wrong"
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"

        Button:
            text: "Go back to Home"
            on_release:
                app.root.current = "home"
                root.manager.transition.direction = "right"
            background_color: (0.51, 0.34, 1.36, 1)

<BackPurificationWindow>:
    name: "backPurification"

    GridLayout:
        cols: 1

        Label:
            text: "Correct! Proceed with the next technique."

        Button:
            text: "Go back to list of purification techniques"
            on_release:
                app.root.current = "purification"

        Button:
            text: "Go back to Home"
            on_release:
                app.root.current = "home"
                root.manager.transition.direction = "right"
            background_color: (0.51, 0.34, 1.36, 1)

<AffinityWindow>:
    name: "affinity"

    GridLayout:
        cols: 1
        Label:
            text: "Affinity chromatography utilizes reversible affinity interaction between target proteins and the stationary phase.\n\nFor example, polyhistidine tag (His-tag) can be used with a nickle column.\n\nIn this setup, the target analyte is eluted with a buffer that contains imidazole. "
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"

        Button:
            text: "Show me how it works!"
            on_release:
                root.showaffinity()
            background_color: (1.36, 2.04, 2.38, 1)
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"

        Button:
            text: "Continue to next question"
            on_release:
                app.root.current = "AffinityQuestion"
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"

        Button:
            text: "Go back to Home"
            on_release:
                app.root.current = "home"
                root.manager.transition.direction = "right"
            background_color: (0.51, 0.34, 1.36, 1)
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"

<AffinityQuestionWindow>:
    name: "AffinityQuestion"

    GridLayout:
        cols: 1
        Label:
            text: "Is affinity chromatography applicable to all proteins?"
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"

        Button:
            text: "Yes, there are no limitations."
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_release:
                app.root.current = "wrong"

        Button:
            text: "No, it has to be of a specific size."
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_release:
                app.root.current = "wrong"

        Button:
            text: "Yes, but the proteins need to be derivatized after extraction."
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_release:
                app.root.current = "wrong"

        Button:
            text: "No, the his-tag needs to be added during the expression step."
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_release:
                app.root.current = "AffinityQb"

        Button:
            text: "Go back to Home"
            on_release:
                app.root.current = "home"
                root.manager.transition.direction = "right"
            background_color: (0.51, 0.34, 1.36, 1)

<AffinityQbWindow>:
    name: "AffinityQb"

    GridLayout:
        cols:1

        Label:
            text: "How do you add his-tags to a protein?"

        Button:
            text: "You mix it with histidine in pH = 10 buffer"
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_release:
                app.root.current = "wrong"

        Button:
            text: "You can only use this method with proteins naturally containing histidine."
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_release:
                app.root.current = "wrong"

        Button:
            text: "You choose a circular vector that has his-tag sequence."
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_release:
                app.root.current = "AffinityQc"

        Button:
            text: "You have to use mammalian expression system."
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_release:
                app.root.current = "wrong"
        Button:
            text: "Go back to Home"
            on_release:
                app.root.current = "home"
                root.manager.transition.direction = "right"
            background_color: (0.51, 0.34, 1.36, 1)

<AffinityQcWindow>:
    name: "AffinityQc"

    GridLayout:
        cols: 1

        Label:
            text: "How do you remove the his-tags after chromatography?"
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"

        Button:
            text: "You don't, they don't change much in the protein."
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_release:
                app.root.current = "wrong"

        Button:
            text: "You use thrombin cleavage kit."
            on_release:
                app.root.current = "AffinityQd"

        Button:
            text: "You use mercaptoethanol."
            on_release:
                app.root.current = "wrong"

        Button:
            text: "You use HindIII enzyme."
            on_release:
                app.root.current = "wrong"
        Button:
            text: "Go back to Home"
            on_release:
                app.root.current = "home"
                root.manager.transition.direction = "right"
            background_color: (0.51, 0.34, 1.36, 1)

<AffinityQdWindow>:
    name: "AffinityQd"

    GridLayout:
        cols: 1

        Label:
            text: "What column would you use in affinity chromatography of a protein with His-tag?"
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"

        Button:
            text: "C18 column"
            on_release:
                app.root.current = "wrong"

        Button:
            text: "Silica hel column"
            on_release:
                app.root.current = "wrong"

        Button:
            text: "Nickel column"
            on_release:
                app.root.current = "AffinityQe"

        Button:
            text: "Desalting column"
            on_release:
                app.root.current = "wrong"
        Button:
            text: "Go back to Home"
            on_release:
                app.root.current = "home"
                root.manager.transition.direction = "right"
            background_color: (0.51, 0.34, 1.36, 1)

<AffinityQeWindow>:
    name: "AffinityQe"

    GridLayout:
        cols: 1

        Label:
            text: "If imidazole is used to elute the target analyte, how can it be later separated from the protein?"
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"

        Button:
            text: "Show imidazole structure"
            on_release:
                root.showimidazole()
            background_color: (1.36, 2.04, 2.38, 1)

        Button:
            text: "Size-exclusion chromatography"
            on_release:
                app.root.current = "final"

        Button:
            text: "Second run on nickel column"
            on_release:
                app.root.current = "wrong"

        Button:
            text: "Extraction with water"
            on_release:
                app.root.current = "wrong"

        Button:
            text: "It evaporates"
            on_release:
                app.root.current = "wrong"
        Button:
            text: "Go back to Home"
            on_release:
                app.root.current = "home"
                root.manager.transition.direction = "right"
            background_color: (0.51, 0.34, 1.36, 1)

<HydrophobicWindow>:
    name: "hydrophobic"

    GridLayout:
        cols: 1
        Label:
            text: "Sample molecules containing hydrophobic and hydrophilic regions\nare applied to an HIC column in a high-salt buffer. The salt in the buffer\nreduces the solvation of sample solutes. As solvation decreases,\nhydrophobic regions that become exposed are adsorbed by the media.\nThe more hydrophobic the molecule, the less salt is needed\nto promote binding."
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"

        Button:
            text: "Show me how HIC works!"
            on_release:
                root.showhic()
            background_color: (1.36, 2.04, 2.38, 1)
        Button:
            text: "Continue to next question"
            on_release:
                app.root.current = "hic2"

        Button:
            text: "Go back to Home"
            on_release:
                app.root.current = "home"
                root.manager.transition.direction = "right"
            background_color: (0.51, 0.34, 1.36, 1)
<hic2Window>:
    name: "hic2"

    GridLayout:
        cols: 1

        Label:
            text: "Amino acids have different levels of hydrophobicity."
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"

        Button:
            text: "Show me how amino acids are classified."
            on_release:
                root.showaa()
            background_color: (1.36, 2.04, 2.38, 1)

        Button:
            text: "Continue to next question"
            on_release:
                app.root.current = "hic3"

        Button:
            text: "Go back to Home"
            on_release:
                app.root.current = "home"
                root.manager.transition.direction = "right"
            background_color: (0.51, 0.34, 1.36, 1)

<hic3Window>:
    name: "hic3"

    GridLayout:
        cols: 1

        Label:
            text: "What possible issues with this separation technique do you see?"
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"

        Button:
            text: "Our protein does not have hydrophobic amino acids."
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_release:
                app.root.current = "wrong"

        Button:
            text: "Our protein does not have hydrophilic amino acids."
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_release:
                app.root.current = "wrong"

        Button:
            text: "We need to use a special vector - to introduce hydrophobic amino acids to our protein."
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_release:
                app.root.current = "wrong"

        Button:
            text: "It is not specific enough - many proteins in E.coli have similar hydrophobicity."
            text_size: root.width, None
            size: self.texture_size
            halign: "center"
            valign: "center"
            on_release:
                app.root.current = "backPurification"

        Button:
            text: "Go back to Home"
            on_release:
                app.root.current = "home"
                root.manager.transition.direction = "right"
            background_color: (0.51, 0.34, 1.36, 1)
<WrongWindow>:
    name: "wrong"

    GridLayout:
        cols: 1

        Label:
            text: "That's not the answer we were looking for."

        Button:
            text: "Try again!"
            on_release:
                app.root.current = "home"
            background_color: (0.51, 0.34, 1.36, 1)
<FinalWindow>:
    name: "final"

    GridLayout:
        cols: 1

        Label:
            text: "Correct!"

        Label:
            text: "Thank you! That's all we had for you."

        Button:
            text: "Show summary of all purification techniques"
            on_release:
                root.showallpurification()
            background_color: (1.36, 2.04, 2.38, 1)
        Button:
            text: "Go back to Home"
            on_release:
                app.root.current = "home"
            background_color: (0.51, 0.34, 1.36, 1)