WindowManager:
    MainWindow:
    SecondWindow:

<MainWindow>:
    name: "main"
    sequence: sequence

    GridLayout:
        cols:1
        size: root.width, root.height

        GridLayout:
            cols:2

            Label:
                text: "Paste the sequence from the FASTA file.\nInclude the header. "

            TextInput:
                id: sequence
                multinline: False

        Button:
            text:"Submit"
            on_release:
                root.btn()
                app.root.current = "second"

<SecondWindow>
    name: "second"

    Button:
        text: "This is second window"
        on_release:
            app.root.current = "main"
