WindowManager:
    HomeWindow:
    MainWindow:
    SecondWindow:
    ProteinWindow:
    ExpressionWindow:
    WrongWindow:
    BacterialWindow:
    PurificationWindow:
    IonExchangeWindow:
    PostAnalysisWindow:
    Expression3Window:
    Expression4Window:
    BamhiWindow:
    SECWindow:
    AffinityWindow:
    HydrophobicWindow:

<HomeWindow>:
    name: "home"

    GridLayout:
        cols: 1
        size: root.width, root.height

        Label:
            text: "Welcome to Biochem 463L Bandersnatch\n Let's start with analysis of your protein. "

        Button:
            text: "Find out protein identity"
            on_release:
                app.root.current = "postanalysis"


<MainWindow>:
    name: "main"
    sequence: sequence

    GridLayout:
        cols:1
        size: root.width, root.height

        GridLayout:
            cols:2

            Label:
                text: "Paste the sequence from the FASTA file.\nInclude the header. "

            TextInput:
                id: sequence
                multinline: False

        Button:
            text:"Submit"
            on_release:
                root.btn()
                app.root.current = "second"

        Button:
            text: "Go back to home screen"
            on_release:
                app.root.current = "home"

<SecondWindow>:
    name: "second"
    inputfasta: inputfasta

    GridLayout:
        cols:1
        size: root.width, root.height

        Label:
            text: "We will use Basic Local Alignment Search Tool (BLAST) to find out the identity of this protein. \n Is the following sequence correct? \n\n BLAST search takes a couple of minutes."

        Label:
            id: inputfasta
            text: "The sequence you entered should appear here. If you don't see it, start over."

        Button:
            text: "I made an error, take me back."
            on_release:
                app.root.current = "main"
                root.manager.transition.direction = "right"

        Button:
            text: "Let's do this!"
            on_release:
                app.root.current = "protein"
                root.blastsearch()
                root.manager.transition.direction = "left"

<ProteinWindow>:
    name: "protein"
    protname: protname
    weight: weight

    GridLayout:
        cols:1
        size: root.width, root.height

        Label:
            text: "Your protein was identified!"

        Label:
            text: "Name of the species it came from is in square brackets [  ]"

        Label:
            id: protname
            text: "Something went wrong, try again!"

        Label:
            text: "Weight of this protein is:"

        Label:
            id: weight
            text: "The weight should appear here, something went wrong"

        Button:
            text: "Continue"
            on_release:
                app.root.current = "postanalysis"

<PostAnalysisWindow>:
    name: "postanalysis"

    GridLayout:
        cols: 1
        size: root.width, root.height

        Label:
            text: "Welcome to Biochem 463L Bandersnatch\n Let's start with analysis of your protein. "

        Button:
            text: "Change the analysed protein"
            on_release:
                app.root.current = "main"

        Button:
            text: "Learn about protein expression"
            on_release:
                app.root.current = "expression"

        Button:
            text: "Learn about protein purification"
            on_release:
                app.root.current = "purification"

<ExpressionWindow>:
    name: "expression"

    GridLayout:
        cols: 1
        size: root.width, root.height

        Label:
            text: "To study a protein, you need to have a sample.\nHow would you like to produce your protein?"

        Button:
            text: "Mammalian cell culture"
            on_release:
                app.root.current = "wrong"

        Button:
            text: "Order it on Amazon"
            on_release:
                app.root.current = "wrong"

        Button:
            text: "Bacterial cell culture"
            on_release:
                app.root.current = "bacterial"

        Button:
            text: "Order it on Fisher Scientific"
            on_release:
                app.root.current = "wrong"

        Button:
            text: "Go back to Home"
            on_release:
                app.root.current = "postanalysis"

<BacterialWindow>:
    name: "bacterial"

    GridLayout:
        cols: 1

        Label:
            text: "You need a circular vector to express your protein in bacteria. \nTypically, pET-3A vector is used."

        Button:
            text: "Show pET-3A vector"
            on_release:
                root.showpet()

        Button:
            text: "Continue to next question"
            on_release:
                app.root.current = "expression3"

        Button:
            text: "Go back to Home"
            on_release:
                app.root.current = "postanalysis"


<Expression3Window>:
    name: "expression3"

    GridLayout:
        cols: 1

        Label:
            text: "How do you incorporate a desired gene into the vector?"

        Button:
            text: "Heat shock"
            on_release:
                app.root.current = "wrong"

        Button:
            text: "Restriction enzymes"
            on_release:
                app.root.current = "expression4"

        Button:
            text: "Synthesize the vector from the bases in a correct sequence"
            on_release:
                app.root.current = "wrong"

        Button:
            text: "Mix the vectors and the DNA for 24h in acidic solution"
            on_release:
                app.root.current = "wrong"

<Expression4Window>:

    name: "expression4"

    GridLayout:
        cols: 2

        Label:
            text: "Which restriction enzyme would you use with this vector?"

        Button:
            text: "Show me the sequence of pET-3A"

        Button:
            text: "NdeI"
            on_release:
                app.root.current = "wrong"

        Button:
            text: "BamHI"
            on_release:
                app.root.current = "bamhi"

        Button:
            text: "HindIII"
            on_release:
                app.root.current = "wrong"

<BamhiWindow>:
    name: "bamhi"

    GridLayout:
        cols: 1

        Label:
            text: "Correct! You are done with this module!"

        Button:
            text: "Continue to Purification Module"
            on_release:
                app.root.current = "purification"

        Button:
            text: "Go back Home"
            on_release:
                app.root.current = "postanalysis"
                root.manager.transition.direction = "right"

<PurificationWindow>:
    name: "purification"

    GridLayout:
        cols:2

        GridLayout:
            cols: 2

            Label:
                text: "Following methods are available:"

            Button:
                text: "Size-exclusion chromatography"
                on_release:
                    app.root.current = "sec"

            Button:
                text: "Ion-exchange chromatography"
                on_release:
                    app.root.current = "ionexchange"

            Button:
                text: "Hydrophobic interaction chromatography"
                on_release:
                    app.root.current = "hydrophobic"

            Button:
                text: "Affinity chromatography"
                on_release:
                    app.root.current = "affinity"

            Button:
                text: "Go back to Home"
                on_release:
                    app.root.current = "postanalysis"
                    root.manager.transition.direction = "right"

<IonExchangeWindow>:
    name: "ionexchange"
    isoelectric: isoelectric

    GridLayout:
        cols: 1
        Label:
            text: "Ion exchange chromatography is <explanation>."

        Label:
            id: isoelectric
            text: "You pI should be displayed here."

        Button:
            text: "Go back to Home"
            on_release:
                app.root.current = "postanalysis"

<SECWindow>:
    name: "sec"

    GridLayout:
        cols: 1
        Label:
            text: "Size exclusion chromatography is <explanation>."

        Button:
            text: "Go back to Home"
            on_release:
                app.root.current = "postanalysis"
                root.manager.transition.direction = "right"

<AffinityWindow>:
    name: "affinity"

    GridLayout:
        cols: 1
        Label:
            text: "Affinity chromatography is <explanation>."
        Button:
            text: "Go back to Home"
            on_release:
                app.root.current = "postanalysis"
                root.manager.transition.direction = "right"


<HydrophobicWindow>:
    name: "hydrophobic"

    GridLayout:
        cols: 1
        Label:
            text: "Ion exchange chromatography is <explanation>."
        Button:
            text: "Go back to Home"
            on_release:
                app.root.current = "postanalysis"
                root.manager.transition.direction = "right"

<WrongWindow>:
    name: "wrong"

    GridLayout:
        cols: 1

        Label:
            text: "That's not correct."

        Button:
            text: "Try again!"
            on_release:
                app.root.current = "postanalysis"
                root.manager.transition.direction = "right"
