WindowManager:
    HomeWindow:
    MainWindow:
    SecondWindow:
    ProteinWindow:
    ExpressionWindow:
    WrongWindow:
    BacterialWindow:
    PurificationWindow:
    IonExchangeWindow:
    PostAnalysisWindow:

<HomeWindow>:
    name: "home"

    GridLayout:
        cols: 1
        size: root.width, root.height

        Label:
            text: "Welcome to Biochem 463L Bandersnatch\n Let's start with analysis of your protein. "

        Button:
            text: "Find out protein identity"
            on_release:
                app.root.current = "main"


<MainWindow>:
    name: "main"
    sequence: sequence

    GridLayout:
        cols:1
        size: root.width, root.height

        GridLayout:
            cols:2

            Label:
                text: "Paste the sequence from the FASTA file.\nInclude the header. "

            TextInput:
                id: sequence
                multinline: False

        Button:
            text:"Submit"
            on_release:
                root.btn()
                app.root.current = "second"

        Button:
            text: "Go back to home screen"
            on_release:
                app.root.current = "home"

<SecondWindow>:
    name: "second"
    inputfasta: inputfasta

    GridLayout:
        cols:1
        size: root.width, root.height

        Label:
            text: "We will use Basic Local Alignment Search Tool (BLAST) to find out the identity of this protein. \n Is the following sequence correct? \n\n BLAST search takes a couple of minutes."

        Label:
            id: inputfasta
            text: "The sequence you entered should appear here. If you don't see it, start over."

        Button:
            text: "I made an error, take me back."
            on_release:
                app.root.current = "main"
                root.manager.transition.direction = "right"

        Button:
            text: "Let's do this!"
            on_release:
                app.root.current = "protein"
                root.blastsearch()
                root.manager.transition.direction = "left"

<ProteinWindow>:
    name: "protein"
    protname: protname
    weight: weight

    GridLayout:
        cols:1
        size: root.width, root.height

        Label:
            text: "Your protein was identified!"

        Label:
            text: "Name of the species it came from is in square brackets [  ]"

        Label:
            id: protname
            text: "Something went wrong, try again!"

        Label:
            text: "Weight of this protein is:"

        Label:
            id: weight
            text: "The weight should appear here, something went wrong"

        Button:
            text: "Continue"
            on_release:
                app.root.current = "postanalysis"

<PostAnalysisWindow>:
    name: "postanalysis"

    GridLayout:
        cols: 1
        size: root.width, root.height

        Label:
            text: "Welcome to Biochem 463L Bandersnatch\n Let's start with analysis of your protein. "

        Button:
            text: "Change the analysed protein"
            on_release:
                app.root.current = "main"

        Button:
            text: "Learn about protein expression"
            on_release:
                app.root.current = "expression"

        Button:
            text: "Learn about protein purification"
            on_release:
                app.root.current = "purification"

<ExpressionWindow>:
    name: "expression"

    GridLayout:
        cols: 1
        size: root.width, root.height

        Label:
            text: "To study a protein, you need to have a sample.\nHow would you like to produce your protein?"

        Button:
            text: "Mammalian cell culture"
            on_release:
                app.root.current = "wrong"

        Button:
            text: "Order it on Amazon"
            on_release:
                app.root.current = "wrong"

        Button:
            text: "Bacterial cell culture"
            on_release:
                app.root.current = "bacterial"

        Button:
            text: "Order it on Fisher Scientific"
            on_release:
                app.root.current = "wrong"

        Button:
            text: "Go back to Home"
            on_release:
                app.root.current = "postanalysis"

<BacterialWindow>:
    name: "bacterial"

    GridLayout:
        cols: 1

        Label:
            text: "You need a circular vector to express your protein in bacteria."

        Button:
            text: "Go back to Home"
            on_release:
                app.root.current = "postanalysis"


<PurificationWindow>:
    name: "purification"

    GridLayout:
        cols:2

        GridLayout:
            cols: 2

            Label:
                text: "Following methods are available:"

            Button:
                text: "Size-exclusion chromatography"

            Button:
                text: "Ion-exchange chromatography"
                on_release:
                    app.root.current = "ionexchange"

            Button:
                text: "Hydrophobic interaction chromatography"

            Button:
                text: "Affinity chromatography"

            Button:
                text: "Go back to Home"
                on_release:
                    app.root.current = "postanalysis"
                    root.manager.transition.direction = "right"

<IonExchangeWindow>:
    name: "ionexchange"
    isoelectric: isoelectric

    GridLayout:
        cols: 1
        Label:
            text: "Ion exchange chromatography is <explanation>."

        Label:
            id: isoelectric
            text: "You pI should be displayed here."

        Button:
            text: "Go back to Home"
            on_release:
                app.root.current = "postanalysis"

<WrongWindow>:
    name: "wrong"

    GridLayout:
        cols: 1

        Label:
            text: "That's not correct."

        Button:
            text: "Try again!"
            on_release:
                app.root.current = "postanalysis"
                root.manager.transition.direction = "right"
